name: Build Docker Image with Packer and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Packer
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://releases.hashicorp.com/packer/1.9.0/packer_1.9.0_linux_amd64.zip
        unzip packer_1.9.0_linux_amd64.zip
        sudo mv packer /usr/local/bin/

    - name: Install AWS CLI
      run: |
        sudo apt-get update -y
        sudo apt-get install -y awscli

    - name: Validate Packer Template
      run: |
        packer validate packer_template.json

    - name: Build Docker Image with Packer
      run: |
        packer build packer_template.json

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.us-east-1 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AKIAZQ3DNW2CD4SUYAEA }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.k9k/GnMD9ooEfJEbfCMphODrYwTrV98DrNAhSX8y}}
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Tag Docker Image for ECR
      run: |
        docker tag rushiks3cloudhub/my-docker-image:latest <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/rushiks3cloudhub/my-docker-image:latest
        docker tag rushiks3cloudhub/my-docker-image:v1.0.0 <aws_account_id>.dkr.ecr.$AWS_REGION.amazonaws.com/rushiks3cloudhub/my-docker-image:v1.0.0

    - name: Push Docker Image to AWS ECR
      run: |
        docker push <6546-5415-8468>.dkr.ecr.$AWS_REGION.amazonaws.com/rushiks3cloudhub/my-docker-image:latest
        docker push <6546-5415-8468>.dkr.ecr.$AWS_REGION.amazonaws.com/rushiks3cloudhub/my-docker-image:v1.0.0
